databases:
  - name: personal_hobbydb
    plan: free
    databaseName: personal_hobby
    user: personal_hobby

services:
  - type: web
    plan: free
    name: personal_hobby
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn personal_hobby.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personal_hobbydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
